### ISSUE TITLE
Bad Guy Teleport

### ISSUE THREAD

**Issue by ShaunDavid1** [PlaceholderGames/2016-Team2Thirds#32]
Just to keep everyone up to date who couldn't make it today, during the session Connor and I discussed how we were going to implement the teleportation of the bad guy. The initial idea was that whenever the good guy used his teleport the bad guy would be forced into teleporting with him. We decided today it may be a better solution to provide the bad guy with a teleport ability of his own, not dependent on power. We could then provide the bad guy with some form of notification when the good guy has teleported, be it an update on his HUD or some in game function. I've taken Connor's code for teleporting and altered/implemented it in the bad guy blueprint. Obviously this can still be changed if people wanted to it's is just what we thought was best today.

**Comment by KieranClarkee** [comment]
The idea itself to give the Bad Guy some more control over certain things is a good one. However I believe that giving him control over the time travelling aspect of the game is not a good idea; I believe this because the idea of the game is that our good guy has crash landed on this planet and is being hunted by a form of savage that has the forest as his hunting ground. His technology consists of ropes and wooden traps, so the technology of our "time travel" may seem odd. However if everyone else is accepting of the idea then I'm fine with it too.

**Comment by Pagec531** [comment]
The idea was mainly for for the demo so the hunter isn't too under powered. I like the idea of the hunter being something to do with time but uses basic methods of hunting maybe?
